CREATE DATABASE THU_VIEN;
USE THU_VIEN;

CREATE TABLE TAC_GIA(
MaTG INT PRIMARY KEY AUTO_INCREMENT,
TenTG VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE SACH(
MaSach INT PRIMARY KEY AUTO_INCREMENT,
TenSach VARCHAR(100) NOT NULL,
NamXuatBan DATE
);
CREATE TABLE SACH_TACGIA(
MaSach INT NOT NULL,
MaTG INT NOT NULL,
FOREIGN KEY(MaSach) REFERENCES SACH(MaSach),
FOREIGN KEY(MaTG) REFERENCES TAC_GIA(MaTG)
);

-- CHEN DU LIEU
INSERT INTO TAC_GIA(TenTG) VALUES
('Nguyễn Du'),
('Bà Huyện Thanh Quan');

INSERT INTO SACH(TenSach, NamXuatBan) VALUES
('Truyện Kiều','2024-01-10'),
('Truyện Kiều 2','2025-02-10');

INSERT INTO SACH_TACGIA(MaTG,MaSach) VALUE(1,1);
INSERT INTO SACH_TACGIA(MaTG,MaSach) VALUE(1,2);

SELECT * FROM TAC_GIA;
SELECT * FROM SACH;
SELECT * FROM SACH_TACGIA;
