CREATE DATABASE TMDT;
USE TMDT;
CREATE TABLE DANH_MUC (
MaDM INT PRIMARY KEY AUTO_INCREMENT,
TenDM varchar(100) NOT NULL UNIQUE
);
CREATE TABLE SAN_PHAM(
MaSP INT PRIMARY KEY AUTO_INCREMENT,
TenSP VARCHAR(150) NOT NULL UNIQUE,
GiaSP DECIMAL(10,2),
CHECK(GiaSP > 0),
MaDM INT NOT NULL,
FOREIGN KEY (MaDM) references DANH_MUC(MaDM)
);

-- Chen du lieu
INSERT INTO DANH_MUC(TENDM) VALUES('AO');
INSERT INTO DANH_MUC(TENDM) VALUES('QUAN');
INSERT INTO DANH_MUC(TENDM) VALUES('MU');

-- LAY DU LIEU BANG DANH MUC
SELECT * FROM DANH_MUC;

-- CHEN DU LIEU BANG SAN PHAM
INSERT INTO SAN_PHAM(TenSP,GiaSP,MaDM) Value ('Ao khoac 01',100,1);
INSERT INTO SAN_PHAM(TenSP,GiaSP,MaDM) Value ('Ao khoac 02',100,1);
INSERT INTO SAN_PHAM(TenSP,GiaSP,MaDM) Value ('Quan kaki 01',300,2);
SELECT * FROM SAN_PHAM;

-- LAY RA THEO DIEU KIEN
SELECT * FROM SAN_PHAM WHERE MaDM=1;
